name: "Get Changed Package List"
description: "Action to get changed packages using list of changed files."

runs:
  using: node24
  main: dist/index.js

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
branding:
  icon: "package"
  color: "gray-dark"

inputs:
  changed-files:
    description: |
      List of changed files.
    required: true
  changed-files-separator:
    description: |
      Separator to split changed files.
    required: true
    default: "\n"
  all-packages:
    description: |
      List of all packages in the project.
    required: true
  all-packages-separator:
    description: |
      Separator to split all packages.
    required: true
    default: "\n"
  changed-packages-format:
    description: |
      Format to return changed packages. Possible values:
        - `list` - list of changed packages
        - `json` - JSON object with changed packages
    required: true
    default: "list"
  changed-packages-relative-path:
    description: |
      If `true`, path are returned relative to the working directory.
      If `false`, absolute paths are returned.
    required: true
    default: "false"
  changed-packages-list-separator:
    description: |
      Used only if `changed-packages-format` is `list`.
      Separator to split changed packages list.
    required: true
    default: "\n"
  package-dependencies-resolution-method:
    description: |
      Method to resolve package dependencies. Possible values:
        - `none` - no dependencies resolution
        - `all` - all packages are considered changed
        - `poetry-path` - dependencies are resolved using path dependencies from `pyproject.toml`
    required: true
    default: "none"
  poetry-path-dependencies-groups:
    description: |
      Used only if `package-dependencies-resolution-method` is `poetry-path`.
      Groups of dependencies to use as depencencies for poetry-path resolution method.
    required: true
    default: "tool.poetry.dependencies"
  poetry-path-dependencies-groups-separator:
    description: |
      Used only if `package-dependencies-resolution-method` is `poetry-path`.
      Separator to split poetry-path dependencies groups.
    required: true
    default: "\n"

outputs:
  changed-packages:
    description: |
      List of changed packages.
