name: "Get Changed Packages"
description: "Action to get changed packages using list of changed files."

inputs:
  changed-files:
    description: "List of changed files."
    required: true
  changed-files-separator:
    description: "Separator to split changed files."
    required: true
    default: "\n"
  package-directory-regex:
    description: "Regex pattern to match package directories."
    required: true
  changed-packages-separator:
    description: "Separator to split changed packages."
    required: true
    default: "\n"

outputs:
  changed-packages:
    description: "List of changed packages."

runs:
  using: node24
  main: dist/index.js

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
branding:
  icon: "message-square"
  color: "gray-dark"
