name: "Get Changed Python Packages"
description: "Get Changed Python Packages Action"

inputs:
  placeholder:
    description: "Placeholder input to be replaced by real inputs"
    required: true
    default: "placeholder"

outputs:
  placeholder:
    description: "Placeholder output to be replaced by real outputs"

runs:
  using: node24
  main: dist/index.js

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
branding:
  icon: "message-square"
  color: "gray-dark"
